//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ── Cluster ───────────────────────────────────────────────────────────────────

func (in *Cluster) DeepCopyInto(out *Cluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

func (in *Cluster) DeepCopy() *Cluster {
	if in == nil {
		return nil
	}
	out := new(Cluster)
	in.DeepCopyInto(out)
	return out
}

func (in *Cluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ClusterList) DeepCopyInto(out *ClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Cluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ClusterList) DeepCopy() *ClusterList {
	if in == nil {
		return nil
	}
	out := new(ClusterList)
	in.DeepCopyInto(out)
	return out
}

func (in *ClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ClusterSpec) DeepCopyInto(out *ClusterSpec) {
	*out = *in
}

func (in *ClusterSpec) DeepCopy() *ClusterSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ClusterStatus) DeepCopyInto(out *ClusterStatus) {
	*out = *in
	if in.ReservedAt != nil {
		in, out := &in.ReservedAt, &out.ReservedAt
		*out = (*in).DeepCopy()
	}
	if in.IdleAt != nil {
		in, out := &in.IdleAt, &out.IdleAt
		*out = (*in).DeepCopy()
	}
	if in.LastRotatedAt != nil {
		in, out := &in.LastRotatedAt, &out.LastRotatedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ClusterStatus) DeepCopy() *ClusterStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// ── ClusterPool ───────────────────────────────────────────────────────────────

func (in *ClusterPool) DeepCopyInto(out *ClusterPool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

func (in *ClusterPool) DeepCopy() *ClusterPool {
	if in == nil {
		return nil
	}
	out := new(ClusterPool)
	in.DeepCopyInto(out)
	return out
}

func (in *ClusterPool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ClusterPoolList) DeepCopyInto(out *ClusterPoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterPool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ClusterPoolList) DeepCopy() *ClusterPoolList {
	if in == nil {
		return nil
	}
	out := new(ClusterPoolList)
	in.DeepCopyInto(out)
	return out
}

func (in *ClusterPoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ClusterPoolSpec) DeepCopyInto(out *ClusterPoolSpec) {
	*out = *in
	out.Template = in.Template
}

func (in *ClusterPoolSpec) DeepCopy() *ClusterPoolSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterPoolSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ClusterTemplate) DeepCopyInto(out *ClusterTemplate) {
	*out = *in
}

func (in *ClusterTemplate) DeepCopy() *ClusterTemplate {
	if in == nil {
		return nil
	}
	out := new(ClusterTemplate)
	in.DeepCopyInto(out)
	return out
}

func (in *ClusterPoolStatus) DeepCopyInto(out *ClusterPoolStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ClusterPoolStatus) DeepCopy() *ClusterPoolStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterPoolStatus)
	in.DeepCopyInto(out)
	return out
}

// ── ClusterPoolAutoscaler ─────────────────────────────────────────────────────

func (in *ClusterPoolAutoscaler) DeepCopyInto(out *ClusterPoolAutoscaler) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

func (in *ClusterPoolAutoscaler) DeepCopy() *ClusterPoolAutoscaler {
	if in == nil {
		return nil
	}
	out := new(ClusterPoolAutoscaler)
	in.DeepCopyInto(out)
	return out
}

func (in *ClusterPoolAutoscaler) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ClusterPoolAutoscalerList) DeepCopyInto(out *ClusterPoolAutoscalerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterPoolAutoscaler, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ClusterPoolAutoscalerList) DeepCopy() *ClusterPoolAutoscalerList {
	if in == nil {
		return nil
	}
	out := new(ClusterPoolAutoscalerList)
	in.DeepCopyInto(out)
	return out
}

func (in *ClusterPoolAutoscalerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ClusterPoolAutoscalerSpec) DeepCopyInto(out *ClusterPoolAutoscalerSpec) {
	*out = *in
	out.TargetRef = in.TargetRef
}

func (in *ClusterPoolAutoscalerSpec) DeepCopy() *ClusterPoolAutoscalerSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterPoolAutoscalerSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *TargetRef) DeepCopyInto(out *TargetRef) {
	*out = *in
}

func (in *TargetRef) DeepCopy() *TargetRef {
	if in == nil {
		return nil
	}
	out := new(TargetRef)
	in.DeepCopyInto(out)
	return out
}

func (in *ClusterPoolAutoscalerStatus) DeepCopyInto(out *ClusterPoolAutoscalerStatus) {
	*out = *in
	if in.LastScaleTime != nil {
		in, out := &in.LastScaleTime, &out.LastScaleTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ClusterPoolAutoscalerStatus) DeepCopy() *ClusterPoolAutoscalerStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterPoolAutoscalerStatus)
	in.DeepCopyInto(out)
	return out
}
