---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: meridian-operator
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - meridian.io
  resources:
  - clusterpoolautoscalers
  - clusterpools
  - clusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - meridian.io
  resources:
  - clusterpoolautoscalers/status
  - clusterpools/status
  - clusters/status
  verbs:
  - get
  - patch
  - update
